### ISSUE TITLE
Password Error on Decrypt to XML

### ISSUE THREAD

**Issue by GuardianMajor** [xeals/signal-back#45]
I am running the latest version after the new build that came after my issue here #38 and I am getting an error for a correct password as follows:

**Command**
` signal-back_windows_amd64.exe format -f XML -o backup.xml signal-2018-12-15-14-23-41.backup`

**Error**
```
Password: panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x5b25a1]

goroutine 1 [running]:
github.com/xeals/signal-back/cmd.XML.func2(0xc000046680, 0xc000138d70, 0x0)
        /home/xeal/go/src/github.com/xeals/signal-back/cmd/format.go:164 +0x61
github.com/xeals/signal-back/types.(*BackupFile).Consume(0xc000480070, 0xc0000d11a0, 0xc00003e210, 0xc0000443e0, 0x0, 0x0)
        /home/xeal/go/src/github.com/xeals/signal-back/types/backup.go:260 +0x15d
github.com/xeals/signal-back/cmd.XML(0xc000480070, 0x651500, 0xc000072018, 0x3, 0x1)
        /home/xeal/go/src/github.com/xeals/signal-back/cmd/format.go:192 +0x229
github.com/xeals/signal-back/cmd.glob..func4(0xc00008a580, 0x0, 0x0)
        /home/xeal/go/src/github.com/xeals/signal-back/cmd/format.go:69 +0x403
github.com/xeals/signal-back/vendor/github.com/urfave/cli.HandleAction(0x5dd6c0, 0x62a308, 0xc00008a580, 0xc000084100, 0x0)
        /home/xeal/go/src/github.com/xeals/signal-back/vendor/github.com/urfave/cli/app.go:490 +0xcf
github.com/xeals/signal-back/vendor/github.com/urfave/cli.Command.Run(0x61bf7b, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x623b9c, 0x1f, 0x629597, ...)
        /home/xeal/go/src/github.com/xeals/signal-back/vendor/github.com/urfave/cli/command.go:210 +0x997
github.com/xeals/signal-back/vendor/github.com/urfave/cli.(*App).Run(0xc0000861a0, 0xc00007a000, 0x7, 0x8, 0x0, 0x0)
        /home/xeal/go/src/github.com/xeals/signal-back/vendor/github.com/urfave/cli/app.go:255 +0x68e
main.main()
        /home/xeal/go/src/github.com/xeals/signal-back/main.go:52 +0x2d7
```

- Operating system: Windows 10 Pro x64
- Build version (`signal-back --version`): signal-back v0.1.7-alpha.1 / proto commit: d6610f0

**Comment by xeals** [comment]
That's interesting, because it shouldn't ever get a nil reference there...

I've pushed a quick update as alpha.2 that should give a little more info here. Download that and try again.

**Comment by GuardianMajor** [comment]
> That's interesting, because it shouldn't ever get a nil reference there...

Right, that's why I wanted to share, wasn't sure what was breaking.

> I've pushed a quick update as alpha.2 that should give a little more info here. Download that and try again.

Will do, and report back, thank you @xeals Alex

**Comment by GuardianMajor** [comment]
Ok, as promised, I ran the newest build (alpha 2) on the same file, added the `-v` to try and solicit more verbose error reporting hopefully to be more helpful. It produced it but after a very long time and it seems to be at least slightly different than the previous error, I will defer to you to tell me what it means and what else you might need - let me know.

```
|> signal-back_windows_amd64.exe format -f XML -o backup.xml signal-2018-12-15-14-23-41.backup -v
Password: runtime: VirtualAlloc of 142606336 bytes failed with errno=1455
fatal error: out of memory

runtime stack:
runtime.throw(0x61eb57, 0xd)
        /usr/lib/go/src/runtime/panic.go:608 +0x79
runtime.sysMap(0xc05b800000, 0x8800000, 0x7cfd98)
        /usr/lib/go/src/runtime/mem_windows.go:122 +0x138
runtime.(*mheap).sysAlloc(0x7b7060, 0x8800000, 0x38000a4169, 0x366fd90)
        /usr/lib/go/src/runtime/malloc.go:619 +0x1d9
runtime.(*mheap).grow(0x7b7060, 0x42a3, 0x0)
        /usr/lib/go/src/runtime/mheap.go:920 +0x49
runtime.(*mheap).allocSpanLocked(0x7b7060, 0x42a3, 0x7cfda8, 0xa)
        /usr/lib/go/src/runtime/mheap.go:848 +0x361
runtime.(*mheap).alloc_m(0x7b7060, 0x42a3, 0x3660101, 0x366fe60)
        /usr/lib/go/src/runtime/mheap.go:692 +0x127
runtime.(*mheap).alloc.func1()
        /usr/lib/go/src/runtime/mheap.go:759 +0x53
runtime.(*mheap).alloc(0x7b7060, 0x42a3, 0x3000101, 0x415cc3)
        /usr/lib/go/src/runtime/mheap.go:758 +0x91
runtime.largeAlloc(0x8545558, 0x440100, 0x29a0000)
        /usr/lib/go/src/runtime/malloc.go:1019 +0x9e
runtime.mallocgc.func1()
        /usr/lib/go/src/runtime/malloc.go:914 +0x4d
runtime.systemstack(0x0)
        /usr/lib/go/src/runtime/asm_amd64.s:351 +0x6b
runtime.mstart()
        /usr/lib/go/src/runtime/proc.go:1229

goroutine 1 [running]:
runtime.systemstack_switch()
        /usr/lib/go/src/runtime/asm_amd64.s:311 fp=0xc000475188 sp=0xc000475180 pc=0x452780
runtime.mallocgc(0x8545558, 0x0, 0x0, 0xc0000984b8)
        /usr/lib/go/src/runtime/malloc.go:913 +0x8d5 fp=0xc000475228 sp=0xc000475188 pc=0x40bd05
runtime.slicebytetostring(0x0, 0xc04b6c8000, 0x8545558, 0xffffc00, 0x0, 0x0)
        /usr/lib/go/src/runtime/string.go:102 +0xa6 fp=0xc000475258 sp=0xc000475228 pc=0x441756
bytes.(*Buffer).String(...)
        /usr/lib/go/src/bytes/buffer.go:66
github.com/xeals/signal-back/cmd.XML.func1(0xc0010c4990, 0xc000cf5d60, 0x0)
        /home/xeal/go/src/github.com/xeals/signal-back/cmd/format.go:158 +0x161 fp=0xc0004752f0 sp=0xc000475258 pc=0x5b2841
github.com/xeals/signal-back/types.(*BackupFile).Consume(0xc000476070, 0xc0000461b0, 0xc0000440c0, 0xc00004a020, 0x0, 0x0)
        /home/xeal/go/src/github.com/xeals/signal-back/types/backup.go:250 +0x250 fp=0xc000475360 sp=0xc0004752f0 pc=0x596330
github.com/xeals/signal-back/cmd.XML(0xc000476070, 0x6527e0, 0xc000080018, 0x3, 0x1)
        /home/xeal/go/src/github.com/xeals/signal-back/cmd/format.go:203 +0x229 fp=0xc0004759c0 sp=0xc000475360 pc=0x5b0659
github.com/xeals/signal-back/cmd.glob..func4(0xc00009c420, 0x0, 0x0)
        /home/xeal/go/src/github.com/xeals/signal-back/cmd/format.go:70 +0x403 fp=0xc000475a60 sp=0xc0004759c0 pc=0x5b2283
github.com/xeals/signal-back/vendor/github.com/urfave/cli.HandleAction(0x5de720, 0x62b5f8, 0xc00009c420, 0xc000094100, 0x0)
        /home/xeal/go/src/github.com/xeals/signal-back/vendor/github.com/urfave/cli/app.go:490 +0xcf fp=0xc000475a88 sp=0xc000475a60 pc=0x50c1cf
github.com/xeals/signal-back/vendor/github.com/urfave/cli.Command.Run(0x61d1db, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x624e86, 0x1f, 0x62a881, ...)
        /home/xeal/go/src/github.com/xeals/signal-back/vendor/github.com/urfave/cli/command.go:210 +0x997 fp=0xc000475cf8 sp=0xc000475a88 pc=0x50d397
github.com/xeals/signal-back/vendor/github.com/urfave/cli.(*App).Run(0xc0000961a0, 0xc00008a000, 0x8, 0x8, 0x0, 0x0)
        /home/xeal/go/src/github.com/xeals/signal-back/vendor/github.com/urfave/cli/app.go:255 +0x68e fp=0xc000475ed0 sp=0xc000475cf8 pc=0x50a4fe
main.main()
        /home/xeal/go/src/github.com/xeals/signal-back/main.go:52 +0x2d7 fp=0xc000475f98 sp=0xc000475ed0 pc=0x5b3fa7
runtime.main()
        /usr/lib/go/src/runtime/proc.go:201 +0x207 fp=0xc000475fe0 sp=0xc000475f98 pc=0x42e237
runtime.goexit()
        /usr/lib/go/src/runtime/asm_amd64.s:1333 +0x1 fp=0xc000475fe8 sp=0xc000475fe0 pc=0x454771
```

**Comment by nathanmerrill** [comment]
I'm also getting the above errors.  In case it helps, I've added my own stack traces.

Prerelease version: 

        2019/12/28 09:29:04 Unexpected error: runtime error: invalid memory address or nil pointer dereference
    2019/12/28 09:29:04 TEMP: statement is 962:3593320649
    2019/12/28 09:29:04 TEMP: statement is &signal.SqlStatement{Statement:(*string)(nil), Parameters:[]*signal.SqlStatement_SqlParameter(nil), XXX_unrecognized:[]uint8{0x95, 0x3c, 0xc9, 0xb8, 0x2d, 0xd6}} goroutine 1 [running]:
    runtime/debug.Stack(0xc00009c000, 0x2, 0xc0001140c0)
            /usr/lib/go/src/runtime/debug/stack.go:24 +0xae
    runtime/debug.PrintStack()
            /usr/lib/go/src/runtime/debug/stack.go:16 +0x29
    github.com/xeals/signal-back/cmd.XML.func2.1(0xc00001c740)
            /home/xeal/go/src/github.com/xeals/signal-back/cmd/format.go:169 +0x149
    panic(0x5e9360, 0x7aa350)
            /usr/lib/go/src/runtime/panic.go:513 +0x1c7
    github.com/xeals/signal-back/cmd.XML.func2(0xc00001c740, 0x0, 0x0)
            /home/xeal/go/src/github.com/xeals/signal-back/cmd/format.go:175 +0x99
    github.com/xeals/signal-back/types.(*BackupFile).Consume(0xc0000f8070, 0xc0000cd1a0, 0xc0000441a0, 0xc000004020, 0x0, 0x0)
            /home/xeal/go/src/github.com/xeals/signal-back/types/backup.go:260 +0x15d
    github.com/xeals/signal-back/cmd.XML(0xc0000f8070, 0x6527e0, 0xc000006008, 0x3, 0x1)
            /home/xeal/go/src/github.com/xeals/signal-back/cmd/format.go:203 +0x229
    github.com/xeals/signal-back/cmd.glob..func4(0xc00008c420, 0x0, 0x0)
            /home/xeal/go/src/github.com/xeals/signal-back/cmd/format.go:70 +0x403
    github.com/xeals/signal-back/vendor/github.com/urfave/cli.HandleAction(0x5de720, 0x62b5f8, 0xc00008c420, 0xc000048100, 0x0)
            /home/xeal/go/src/github.com/xeals/signal-back/vendor/github.com/urfave/cli/app.go:490 +0xcf
    github.com/xeals/signal-back/vendor/github.com/urfave/cli.Command.Run(0x61d1db, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x624e86, 0x1f, 0x62a881, ...)
            /home/xeal/go/src/github.com/xeals/signal-back/vendor/github.com/urfave/cli/command.go:210 +0x997
    github.com/xeals/signal-back/vendor/github.com/urfave/cli.(*App).Run(0xc0000881a0, 0xc000080000, 0xa, 0x10, 0x0, 0x0)
            /home/xeal/go/src/github.com/xeals/signal-back/vendor/github.com/urfave/cli/app.go:255 +0x68e
    main.main()
            /home/xeal/go/src/github.com/xeals/signal-back/main.go:52 +0x2d7

Stable version:

    panic: runtime error: invalid memory address or nil pointer dereference
    [signal 0xc0000005 code=0x0 addr=0x8 pc=0x57b9bf]

    goroutine 1 [running]:
    github.com/xeals/signal-back/cmd.XML(0xc0420d40e0, 0x606e40, 0xc042004008, 0x3, 0x1)
            /home/xeal/.local/share/go/src/github.com/xeals/signal-back/cmd/format.go:160 +0x15f
    github.com/xeals/signal-back/cmd.glob..func4(0xc04208c420, 0x0, 0x0)
            /home/xeal/.local/share/go/src/github.com/xeals/signal-back/cmd/format.go:67 +0x416
    github.com/xeals/signal-back/vendor/github.com/urfave/cli.HandleAction(0x5a6140, 0x5ef668, 0xc04208c420, 0xc042056100, 0x0)
            /home/xeal/.local/share/go/src/github.com/xeals/signal-back/vendor/github.com/urfave/cli/app.go:490 +0xcf
    github.com/xeals/signal-back/vendor/github.com/urfave/cli.Command.Run(0x5e20ed, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x5e96cb, 0x1f, 0x5ee97c, ...)
            /home/xeal/.local/share/go/src/github.com/xeals/signal-back/vendor/github.com/urfave/cli/command.go:210 +0xa3d
    github.com/xeals/signal-back/vendor/github.com/urfave/cli.(*App).Run(0xc0420881a0, 0xc042080000, 0xa, 0x10, 0x0, 0x0)
            /home/xeal/.local/share/go/src/github.com/xeals/signal-back/vendor/github.com/urfave/cli/app.go:255 +0x6a7
    main.main()
            /home/xeal/.local/share/go/src/github.com/xeals/signal-back/main.go:52 +0x31e
